[project]
name = "farmin-ai"
version = "0.1.0"
description = "Smart farming assistant using Streamlit"
authors = [{ name = "C V VISHNU VARDHAN CHARY" }]
dependencies = [
    "streamlit>=1.30.0",
    "googletrans==4.0.0rc1",
    "Pillow"
]

[tool.setuptools.packages.find]
include = ["components"]  # Only include your Python package
